### ISSUE TITLE
Improve error checking and add debug logs

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/sapphire.py#19]
Improve error checking and add debug logs

**Comment by trentmc** [comment]
@trizin Oasis was going to start with sapphire.py and improve it. Do check with Oasis to avoid redundant work (or I can - lmk)

**Comment by trizin** [comment]
It's been 6 months since that was mentioned, with no updates since, or at least none that I'm aware of. These are tiny tweaks, not taking much effort, already merged the pr :raised_hands:

**Comment by trentmc** [comment]
Good point!
